export const PATH_BASE_AVATAR = 'https://sso.inet.vn/uploads/';
export const DEFAULT_NO_AVATAR = '/src/assets/images/no-avatar.png';
export const errorServer = { error: 'Internal server error' };
export const errorUnknown = 'Unknown error!';
export const errorMsg = { error: 'Invalid request' };
export const notFoundMsg = { error: 'Data does not exist' };
export const isDataValid = { error: 'Please check again' };
export const jwtNotVerify = { error: 'Invalid request or not have access' };
export const isTokenValid = { error: 'Token is not invalid' };
